apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-deployment
spec:
  replicas: 3
  selector:
    matchLabels:  
      app: url
  template: 
    metadata:
      labels:
        app: url
    spec:
      containers:
      - name: url
        image: summerxia2009/wcsc_url:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: url-service
spec:
  selector:
    app: url
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30001
    port: 5001
    targetPort: 5001
