apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 3
  selector:
    matchLabels:  
      app: users
  template: 
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: url
        image: summerxia2009/wcsc_users:latest
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30002
    port: 5002
    targetPort: 5002
    